# This file has been generated by mavenix-2.3.3. Configure the build here!
let mavenix-src = fetchTarball {
      url = "https://github.com/coingaming/mavenix/tarball/f42e469732861136fced1cbfecce94f4479deeff";
      sha256 = "12a6b9r83j9kxqqvvmdjr9a1pw5mcbp0ywj8cnz8jviv2mwrnkmq";
    };
in {
  # pkgs is pinned to 19.09 in mavenix-src,
  # replace/invoke with <nixpkgs> or /path/to/your/nixpkgs_checkout
  pkgs ? (import mavenix-src {}).pkgs,
  mavenix ? import mavenix-src { inherit pkgs; },
  src ? ./.,
  doCheck ? false,
  executable ? true,
}:
with pkgs;
mavenix.buildMaven {
  inherit src;
  debug = true;
  doCheck = false;
  infoFile = ./mavenix.lock;

  # Add build dependencies
  #
  buildInputs = [ unzip ];
  propagatedBuildInputs = [ jq jdk11 ];

  # Set build environment variables
  #
  TERM="xterm-256color";
  MAVEN_OPTS="-Dfile.encoding=UTF-8 -Dnix-build.skip=true";

  # Attributes are passed to the underlying `stdenv.mkDerivation`, so build
  #   hooks can be set here also.
  #
  preBuild = ''
    rm -rf ./.git
  '';

  postInstall = if executable then ''
    export THIS_DIST="eclair-node-0.5.1-SNAPSHOT-\''${git.commit.id.abbrev}"
    (cd ./eclair-node/target/ && \
      unzip -o "./$THIS_DIST-bin.zip"
      cp -R "./$THIS_DIST/." "$out")
  '' else '''';

    #  rm -rf "./$THIS_DIST")

  # Add extra maven dependencies which might not have been picked up
  #   automatically
  #
  #deps = [
  #  { path = "org/group-id/artifactId/version/file.jar"; sha1 = "0123456789abcdef"; }
  #  { path = "org/group-id/artifactId/version/file.pom"; sha1 = "123456789abcdef0"; }
  #];

  # Add dependencies on other mavenix derivations
  #
  #drvs = [ (import ../other/mavenix/derivation {}) ];

  # Override which maven package to build with
  #
  maven = maven.overrideAttrs (_: { jdk = jdk11; });

  # Override remote repository URLs and settings.xml
  #
  #remotes = { central = "https://repo.maven.apache.org/maven2"; };
  #settings = ./settings.xml;
}
