{
 "title": "Akka Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time in Mailbox (Channel)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(akka_group_time_in_mailbox_seconds_count{group=\"eclair-node/user/SimpleSupervisor/Switchboard/Peer/Channel\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing time(Channel)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(akka_group_processing_time_seconds_count{group=\"eclair-node/user/SimpleSupervisor/Switchboard/Peer/Channel\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Register", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Time in Mailbox (Register)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(akka_group_time_in_mailbox_seconds_count{group=\"eclair-node/user/SimpleSupervisor/Register\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing time (Register)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(akka_group_processing_time_seconds_count{group=\"eclair-node/user/SimpleSupervisor/Register\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Time in Mailbox (Peers)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(akka_group_time_in_mailbox_seconds_count{group=\"eclair-node/user/SimpleSupervisor/Switchboard/Peer\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing time(Peer)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(akka_group_processing_time_seconds_count{group=\"eclair-node/user/SimpleSupervisor/Switchboard/Peer\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}