{
 "title": "Eclair Metrics ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Peers Connected",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(peers_connected)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peers Initializing/Initialized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "peerconnections_connecting_total{state=\"initializing\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "peerconnections_connecting_total{state=\"initialized\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers Authenticated/Authenticating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "peerconnections_connecting_total{state=\"authenticating\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "peerconnections_connecting_total{state=\"authenticated\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bitcoin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Bitcoin Balance(BTC)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "bitcoin_balance{status=\"safe\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bitcoin_balance{status=\"unsafe\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bitcoin_balance{status=\"confirmed\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bitcoin_balance{status=\"unconfirmed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utxo Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "bitcoin_utxo_count{status=\"confirmed\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bitcoin_utxo_count{status=\"unconfirmed\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bitcoin_utxo_count{status=\"safe\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bitcoin_utxo_count{status=\"unsafe\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitcoin mempool min feerate per kw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(bitcoin_mempool_min_feerate_per_kw)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Channels",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "channels_count{state=\"OFFLINE\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "channels_count{state=\"CLOSED\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "channels_count{state=\"WAIT_FOR_ACCEPT_CHANNEL\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "channels_count{state=\"WAIT_FOR_FUNDING_CONFIRMED\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channels local feerate per kq",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "rate(channels_local_feerate_per_kw[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Messages Processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "channels_messages_processed_seconds_count{MessageType=\"AcceptChannel\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "channels_messages_processed_seconds_count{MessageType=\"ChannelReestablish\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "channels_messages_processed_seconds_sum{MessageType=\"Error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channels errors total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "channels_errors_total{fatal=\"false\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}