{
 "title": "eclair Host Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(rate(host_load_average[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory and File System Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swap Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "rate(host_swap_usage[1m])", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "rate(host_memory_usage[1m])", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "host_memory_usage", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Host Storage",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "host_storage_mount_space_total_bytes",
       "legendFormat": "__auto"
      },
      {
       "expr": "host_storage_mount_space_free_bytes",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host network data read/write bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(host_network_data_read_bytes_total[1m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(host_network_data_write_bytes_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Host network packet read/write",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(host_network_packets_read_total[1m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(host_network_packets_write_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Overall",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(host_cpu_usage_sum{mode=\"system\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(host_cpu_usage_sum{mode=\"user\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(host_cpu_usage_sum{mode=\"system\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}