// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package lightning


import com.trueaccord.scalapb.Descriptors

@SerialVersionUID(0L)
final case class update_accept(
    sig: lightning.signature,
    revocationHash: lightning.sha256_hash
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[update_accept] with com.trueaccord.lenses.Updatable[update_accept] {
    @transient
    lazy val serializedSize: Int = {
      var __size = 0
      __size += 1 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(sig.serializedSize) + sig.serializedSize
      __size += 1 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(revocationHash.serializedSize) + revocationHash.serializedSize
      __size
    }
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      output.writeTag(1, 2)
      output.writeRawVarint32(sig.serializedSize)
      sig.writeTo(output)
      output.writeTag(3, 2)
      output.writeRawVarint32(revocationHash.serializedSize)
      revocationHash.writeTo(output)
    }
    def mergeFrom(__input: com.google.protobuf.CodedInputStream): lightning.update_accept = {
      var __sig = this.sig
      var __revocationHash = this.revocationHash
      var _done__ = false
      while (!_done__) {
        val _tag__ = __input.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __sig = com.trueaccord.scalapb.LiteParser.readMessage(__input, __sig)
          case 26 =>
            __revocationHash = com.trueaccord.scalapb.LiteParser.readMessage(__input, __revocationHash)
          case tag => __input.skipField(tag)
        }
      }
      lightning.update_accept(
          sig = __sig,
          revocationHash = __revocationHash
      )
    }
    def withSig(__v: lightning.signature): update_accept = copy(sig = __v)
    def withRevocationHash(__v: lightning.sha256_hash): update_accept = copy(revocationHash = __v)
    def getField(__field: Descriptors.FieldDescriptor): Any = {
      __field.number match {
        case 1 => sig
        case 3 => revocationHash
      }
    }
    def companion = lightning.update_accept
}

object update_accept extends com.trueaccord.scalapb.GeneratedMessageCompanion[update_accept]  {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[update_accept]  = this
  def fromFieldsMap(fieldsMap: Map[Int, Any]): lightning.update_accept = lightning.update_accept(
    sig = fieldsMap(1).asInstanceOf[lightning.signature],
    revocationHash = fieldsMap(3).asInstanceOf[lightning.sha256_hash]
  )
  lazy val descriptor = new Descriptors.MessageDescriptor("update_accept", this,
    None, m = Seq(),
    e = Seq(),
    f = lightning.InternalFields_srcMainProtobufLightningProto.internalFieldsFor("lightning.update_accept"))
  lazy val defaultInstance = lightning.update_accept(
    sig = lightning.signature.defaultInstance,
    revocationHash = lightning.sha256_hash.defaultInstance
  )
  implicit class update_acceptLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, update_accept]) extends com.trueaccord.lenses.ObjectLens[UpperPB, update_accept](_l) {
    def sig: com.trueaccord.lenses.Lens[UpperPB, lightning.signature] = field(_.sig)((c_, f_) => c_.copy(sig = f_))
    def revocationHash: com.trueaccord.lenses.Lens[UpperPB, lightning.sha256_hash] = field(_.revocationHash)((c_, f_) => c_.copy(revocationHash = f_))
  }
  final val SIG_FIELD_NUMBER = 1
  final val REVOCATION_HASH_FIELD_NUMBER = 3
}
