// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package lightning


import com.trueaccord.scalapb.Descriptors

@SerialVersionUID(0L)
final case class update_complete(
    revocationPreimage: lightning.sha256_hash
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[update_complete] with com.trueaccord.lenses.Updatable[update_complete] {
    @transient
    lazy val serializedSize: Int = {
      var __size = 0
      __size += 1 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(revocationPreimage.serializedSize) + revocationPreimage.serializedSize
      __size
    }
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      output.writeTag(1, 2)
      output.writeRawVarint32(revocationPreimage.serializedSize)
      revocationPreimage.writeTo(output)
    }
    def mergeFrom(__input: com.google.protobuf.CodedInputStream): lightning.update_complete = {
      var __revocationPreimage = this.revocationPreimage
      var _done__ = false
      while (!_done__) {
        val _tag__ = __input.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __revocationPreimage = com.trueaccord.scalapb.LiteParser.readMessage(__input, __revocationPreimage)
          case tag => __input.skipField(tag)
        }
      }
      lightning.update_complete(
          revocationPreimage = __revocationPreimage
      )
    }
    def withRevocationPreimage(__v: lightning.sha256_hash): update_complete = copy(revocationPreimage = __v)
    def getField(__field: Descriptors.FieldDescriptor): Any = {
      __field.number match {
        case 1 => revocationPreimage
      }
    }
    def companion = lightning.update_complete
}

object update_complete extends com.trueaccord.scalapb.GeneratedMessageCompanion[update_complete]  {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[update_complete]  = this
  def fromFieldsMap(fieldsMap: Map[Int, Any]): lightning.update_complete = lightning.update_complete(
    revocationPreimage = fieldsMap(1).asInstanceOf[lightning.sha256_hash]
  )
  lazy val descriptor = new Descriptors.MessageDescriptor("update_complete", this,
    None, m = Seq(),
    e = Seq(),
    f = lightning.InternalFields_srcMainProtobufLightningProto.internalFieldsFor("lightning.update_complete"))
  lazy val defaultInstance = lightning.update_complete(
    revocationPreimage = lightning.sha256_hash.defaultInstance
  )
  implicit class update_completeLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, update_complete]) extends com.trueaccord.lenses.ObjectLens[UpperPB, update_complete](_l) {
    def revocationPreimage: com.trueaccord.lenses.Lens[UpperPB, lightning.sha256_hash] = field(_.revocationPreimage)((c_, f_) => c_.copy(revocationPreimage = f_))
  }
  final val REVOCATION_PREIMAGE_FIELD_NUMBER = 1
}
