// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package lightning


import com.trueaccord.scalapb.Descriptors

@SerialVersionUID(0L)
final case class update(
    revocationHash: lightning.sha256_hash,
    delta: Long
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[update] with com.trueaccord.lenses.Updatable[update] {
    @transient
    lazy val serializedSize: Int = {
      var __size = 0
      __size += 1 + com.google.protobuf.CodedOutputStream.computeRawVarint32Size(revocationHash.serializedSize) + revocationHash.serializedSize
      __size += com.google.protobuf.CodedOutputStream.computeSInt64Size(2, delta)
      __size
    }
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      output.writeTag(1, 2)
      output.writeRawVarint32(revocationHash.serializedSize)
      revocationHash.writeTo(output)
      output.writeSInt64(2, delta)
    }
    def mergeFrom(__input: com.google.protobuf.CodedInputStream): lightning.update = {
      var __revocationHash = this.revocationHash
      var __delta = this.delta
      var _done__ = false
      while (!_done__) {
        val _tag__ = __input.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __revocationHash = com.trueaccord.scalapb.LiteParser.readMessage(__input, __revocationHash)
          case 16 =>
            __delta = __input.readSInt64()
          case tag => __input.skipField(tag)
        }
      }
      lightning.update(
          revocationHash = __revocationHash,
          delta = __delta
      )
    }
    def withRevocationHash(__v: lightning.sha256_hash): update = copy(revocationHash = __v)
    def withDelta(__v: Long): update = copy(delta = __v)
    def getField(__field: Descriptors.FieldDescriptor): Any = {
      __field.number match {
        case 1 => revocationHash
        case 2 => delta
      }
    }
    def companion = lightning.update
}

object update extends com.trueaccord.scalapb.GeneratedMessageCompanion[update]  {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[update]  = this
  def fromFieldsMap(fieldsMap: Map[Int, Any]): lightning.update = lightning.update(
    revocationHash = fieldsMap(1).asInstanceOf[lightning.sha256_hash],
    delta = fieldsMap(2).asInstanceOf[Long]
  )
  lazy val descriptor = new Descriptors.MessageDescriptor("update", this,
    None, m = Seq(),
    e = Seq(),
    f = lightning.InternalFields_srcMainProtobufLightningProto.internalFieldsFor("lightning.update"))
  lazy val defaultInstance = lightning.update(
    revocationHash = lightning.sha256_hash.defaultInstance,
    delta = 0L
  )
  implicit class updateLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, update]) extends com.trueaccord.lenses.ObjectLens[UpperPB, update](_l) {
    def revocationHash: com.trueaccord.lenses.Lens[UpperPB, lightning.sha256_hash] = field(_.revocationHash)((c_, f_) => c_.copy(revocationHash = f_))
    def delta: com.trueaccord.lenses.Lens[UpperPB, Long] = field(_.delta)((c_, f_) => c_.copy(delta = f_))
  }
  final val REVOCATION_HASH_FIELD_NUMBER = 1
  final val DELTA_FIELD_NUMBER = 2
}
