# Commits which cross over still get resolved.
# Initial state: A=1000000, B=0, both fee rates=10000
A:offer 500000000,b8928207364d445daa42f4ba8be0ef661b8d7190206c01f6ee8281566b3dec0a
B:recvoffer
A:commit
B:recvcommit
A:recvrevoke
B:commit
A:recvcommit
B:recvrevoke

B:fulfill 1,60303ae22b998861bce3b28f33eec1be758a213c86c93c076dbe9f558c11c752
B:commit
A:recvremove
A:recvcommit
B:recvrevoke
A:commit
B:recvcommit
A:recvrevoke

# Intermediate state: A=500000, B=500000, both fee rates=10000
echo ***A (intermediate)***
A:dump
echo ***B (intermediate)***
B:dump

A:offer 1000000,7b3d979ca8330a94fa7e9e1b466d8b99e0bcdea1ec90596c0dcc8d7ef6b4300c
B:offer 2000000,6016bcc377c93692f2fe19fbad47eee6fb8f4cc98c56e935db5edb69806d84f6
A:commit
B:commit

A:recvoffer
B:recvoffer
A:recvcommit
B:recvcommit

A:recvrevoke
B:recvrevoke

# They've got to come into sync eventually!
A:commit
B:commit
A:recvcommit
B:recvcommit
A:recvrevoke
B:recvrevoke

checksync
echo ***A***
A:dump
echo ***B***
B:dump
