name: Latest Bitcoin Core

on:
  schedule:
    # Run at midnight on Sunday and Wednesday.
    - cron: '0 0 * * 0,3'

permissions:
  contents: read

jobs:

  regression-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout bitcoind master
        uses: actions/checkout@v3
        with:
          repository: bitcoin/bitcoin
          path: bitcoin

      - name: Install bitcoind dependencies
        run: sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev                                                                                          libminiupnpc-dev libnatpmp-dev    libzmq3-dev                                        libsqlite3-dev            systemtap-sdt-dev
        working-directory: ./bitcoin

      - name: Autogen bitcoind
        run: ./autogen.sh
        working-directory: ./bitcoin

      - name: Configure bitcoind
        run: ./configure --with-zmq --without-gui --disable-shared --with-pic --disable-tests --disable-bench
        working-directory: ./bitcoin

      - name: Build bitcoind
        run: make -j "$(($(nproc)))"
        working-directory: ./bitcoin

      - name: Checkout eclair master
        uses: actions/checkout@v3
        with:
          path: eclair

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Configure OS settings
        run: echo "fs.file-max = 1024000" | sudo tee -a /etc/sysctl.conf

      - name: Run eclair tests
        run: BITCOIND_DIR=$GITHUB_WORKSPACE/bitcoin/src mvn test
        working-directory: ./eclair
